routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
	return view('welcome');
});
Route::resource('checkout', 'OrderController');
Route::post('paypal', 'OrderController@paypal')->name('checkout.paypal');
Route::get('returnPaypal', 'OrderController@returnPaypal')->name('process.paypal');
Route::get('cancelPaypal', 'OrderController@cancelPaypal')->name('cancel.paypal');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
	Route::get('/', 'ProductController@show')->name('all');
	Route::get('/{product}', 'ProductController@single')->name('single');
	Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('addToCart');
});

Route::group(['as' => 'cart.', 'prefix' => 'cart'], function () {
	Route::get('/', 'ProductController@cart')->name('all');
	Route::post('/remove/{product}', 'ProductController@removeProduct')->name('remove');
	Route::post('/update/{product}', 'ProductController@updateProduct')->name('update');
});

Route::group(['as' => 'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function () {
	Route::get('/', 'AdminController@dashboard');
	Route::get('category/{category}/remove', 'CategoryController@remove')->name('category.remove');
	Route::get('category/trash', 'CategoryController@trash')->name('category.trash');
	Route::get('category/recover/{id}', 'CategoryController@recoverCat')->name('category.recover');
	Route::get('product/{product}/remove', 'ProductController@remove')->name('product.remove');
	Route::get('product/trash', 'ProductController@trash')->name('product.trash');
	Route::get('product/recover/{id}', 'ProductController@recoverProduct')->name('product.recover');

	Route::view('product/extras', 'admin.partials.extras')->name('product.extras');

	Route::get('profile/{profile}/remove', 'ProfileController@remove')->name('profile.remove');
	Route::get('profile/trash', 'ProfileController@trash')->name('profile.trash');
	Route::get('profile/recover/{id}', 'ProfileController@recoverProduct')->name('profile.recover');
	Route::view('profile/roles', 'admin.partials.extras')->name('profile.extras');

	Route::get('profile/states/{id?}', 'ProfileController@getStates')->name('profile.states');
	Route::get('profile/cities/{id?}', 'ProfileController@getCities')->name('profile.cities');

	Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');
	Route::resource('product', 'ProductController');
	Route::resource('category', 'CategoryController');
	Route::resource('profile', 'ProfileController');
});
Route::get('bydate', function(){
	return \App\User::where('created_at','=', '2019-03-22 12:50:23')->get();
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Product;
use App\CategoryParent;

class Category extends Model
{
	 use SoftDeletes;

     protected $guarded = [];

     protected $dates = ['deleted_at'];
    
     public function products(){
    	return $this->belongsToMany('App\Product', 'category_product');
    }
    public function childrens(){
        return $this->belongsToMany(Category::class,'category_parent','parent_id','category_id');
    }
    public function parents(){
        return $this->belongsToMany(Category::class,'category_parent','category_id','parent_id');
    }
	public function getRouteKeyName(){
   	 return 'slug';
	}

}

resources/views/admin/categories/create.blade.php
@extends('admin.app')
@section('breadcrumbs')
	<li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
	<li class="breadcrumb-item"><a href="{{route('admin.category.index')}}">Categories</a></li>
	<li class="breadcrumb-item active" aria-current="page">Add/Edit Category</li>
@endsection
@section('content')
<form action="@if(isset($category)) {{route('admin.category.update', $category)}} @else {{route('admin.category.store')}} @endif" method="post" accept-charset="utf-8">
	@csrf
	@if(isset($category))
		@method('PUT')
	@endif
	<div class="form-group row">
		<div class="col-sm-12">
			@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
		</div>
		<div class="col-sm-12">
			@if (session()->has('message'))
			<div class="alert alert-success">
				{{session('message')}}
			</div>
			@endif
		</div>
		<div class="col-sm-12">
			<label class="form-control-label">Title: </label>
			<input type="text" id="txturl" name="title" class="form-control " value="{{@$category->title}}">
			<p class="small">{{config('app.url')}}<span id="url">{{@$category->slug}}</span></p>
			<input type="hidden" name="slug" id="slug" value="{{@$category->slug}}">
		</div>
	</div>
	<div class="form-group row">
		
		<div class="col-sm-12">
			<label class="form-control-label">Description: </label>
			<textarea name="description" id="editor" class="form-control " rows="10" cols="80">{!! @$category->description !!}</textarea>
		</div>
	</div>
	<div class="form-group row">
		@php 
			$ids = (isset($category->parents) && $category->parents->count() > 0 ) ? array_pluck($category->parents, 'id') : null
		@endphp
		<div class="col-sm-12">
			<label class="form-control-label">Select Category: </label>
			<select name="parent_id[]" id="parent_id" class="form-control" multiple>
				@if(isset($categories))
				<option value="0">Top Level</option>
				@foreach($categories as $cat)
				<option value="{{$cat->id}}" @if(!is_null($ids) && in_array($cat->id, $ids)) {{'selected'}} @endif>{{$cat->title}}</option>
				@endforeach
				@endif
				option
			</select>
		</div>
	</div>
	<div class="form-group row">
		<div class="col-sm-12">
			@if(isset($category))
			<input type="submit" name="submit" class="btn btn-primary" value="Edit Category" />
			@else
			<input type="submit" name="submit" class="btn btn-primary" value="Add Category" />
			@endif
		</div>
		
	</div>
	
</form>
@endsection
@section('scripts')
<script type="text/javascript">
$(function(){
	ClassicEditor.create( document.querySelector( '#editor' ), {
		toolbar: [ 'Heading', 'Link', 'bold', 'italic', 'bulletedList', 'numberedList', 'blockQuote','undo', 'redo' ],
	}).then( editor => {
		console.log( editor );
	}).catch( error => {
		console.error( error );
	});
	$('#txturl').on('keyup', function(){
		var url = slugify($(this).val());
		$('#url').html(url);
		$('#slug').val(url);
	})
	$('#parent_id').select2({
		placeholder: "Select a Parent Category",
		allowClear: true,
		minimumResultsForSearch: Infinity
	});
})
</script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.app')
@section('breadcrumbs')
<li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
<li class="breadcrumb-item active" aria-current="page">Categories</li>
@endsection
@section('content')
<div class="row d-block">
  <div class="col-sm-12">
    @if (session()->has('message'))
    <div class="alert alert-success">
      {{session('message')}}
    </div>
    @endif
  </div>
</div>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h2 class="h2">Categories List</h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <a href="{{route('admin.category.create')}}" class="btn btn-sm btn-outline-secondary">
      Add Category
    </a>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Slug</th>
        <th>Childrens</th>
        <th>Date Created</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      @if($categories->count() > 0)
      @foreach($categories as $category)
      <tr>
        <td>{{$category->id}}</td>
        <td>{{$category->title}}</td>
        <td>{!! $category->description !!}</td>
        <td>{{$category->slug}}</td>
        <td>
          @if($category->childrens()->count() > 0)
          @foreach($category->childrens as $children)
          {{$children->title}},
          @endforeach
          @else
          <strong>{{"Parent Category"}}</strong>
          @endif
        </td>
        @if($category->trashed())
        <td>{{$category->deleted_at}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('admin.category.recover',$category->id)}}">Restore</a> | <a class="btn btn-danger btn-sm" href="javascript:;" onclick="confirmDelete('{{$category->id}}')">Delete</a>
        <form id="delete-category-{{$category->id}}" action="{{ route('admin.category.destroy', $category->slug) }}" method="POST" style="display: none;">
          
          @method('DELETE')
          @csrf
        </form>
      </td>
      @else
      <td>{{$category->created_at}}</td>
      <td><a class="btn btn-info btn-sm" href="{{route('admin.category.edit',$category->slug)}}">Edit</a> | <a id="trash-category-{{$category->id}}" class="btn btn-warning btn-sm" href="{{route('admin.category.remove',$category->slug)}}">Trash</a> | <a class="btn btn-danger btn-sm" href="javascript:;" onclick="confirmDelete('{{$category->id}}')">Delete</a>
      <form id="delete-category-{{$category->id}}" action="{{ route('admin.category.destroy', $category->slug) }}" method="POST" style="display: none;">
        
        @method('DELETE')
        @csrf
      </form>
    </td>
    @endif
  </tr>
  @endforeach
  @else
  <tr>
    <td colspan="7" class="alert alert-info">No Categories Found..</td>
  </tr>
  @endif
  
</tbody>

</table>
</div>
<div class="row">
<div class="col-md-12">
{{$categories->links()}}
</div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
function confirmDelete(id){
let choice = confirm("Are You sure, You want to Delete this record ?")
if(choice){
document.getElementById('delete-category-'+id).submit();
}
}
</script>
@endsection